// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzfsbscvvzsxvdxdxlli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6ZnNic2N2dnpzeHZkeGR4bGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyODQ2MTEsImV4cCI6MjA4OTg2MDYxMX0.bHqAuXse_2aLZwvFy_HgiiTop-gHIgT1_iRImS3RMkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});